title: blank
first_name: Vyacheslav
middle_name: null
last_name: Goryunov
email: inbox@vyacheslav.me
description: |
  Principal Software Engineer, GoLang, PHP, YouTube author.
footer_text: ''
keywords: 'software-engineer,golang,vyacheslav-goryunov,viacheslav-goriunov,portfolio-website'
lang: en
icon: "\U0001F9E9"
url: 'https://vyacheslav.me'
baseurl: null
last_updated: false
impressum_path: null
rss_icon: false
navbar_fixed: true
footer_fixed: false
max_width: 800px
serve_og_meta: false
serve_schema_org: false
og_image: null
telegram: VyacheslavG
github_username: Vyache18
gitlab_username: null
twitter_username: null
linkedin_username: vyacheslav-goryunov-579075191
scholar_userid: null
orcid_id: null
medium_username: null
quora_username: null
publons_id: null
research_gate_profile: null
blogger_url: null
work_url: null
keybase_username: null
wikidata_id: null
dblp_url: null
stackoverflow_id: null
contact_note: 'Feel free to write me to <a href="https://t.me/VyacheslavG">Telegram!</a>'
google_analytics: G-YZBG52JPFY
google_site_verification: null
bing_site_verification: null
panelbear_analytics: null
blog_name: vyacheslav
blog_nav_title: null
blog_description: 'Vyacheslav Goryunov personal portfolio website.'
permalink: '/blog/:year/:title/'
pagination:
  enabled: true
disqus_shortname: vyacheslav
external_sources: null
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: '/news/:path/'
  projects:
    output: true
    permalink: '/projects/:path/'
news_limit: 5
markdown: kramdown
highlighter: rouge
highlight_theme_light: github
highlight_theme_dark: native
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
  - _pages
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jemoji
defaults:
  - scope:
      path: assets/**/*.*
    values:
      sitemap: false
jekyll-minifier:
  exclude:
    - robots.txt
  uglifier_args:
    harmony: true
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'
scholar:
  last_name: ''
  first_name: ''
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
    - latex
    - smallcaps
    - superscript
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: '@*'
filtered_bibtex_keywords:
  - abbr
  - abstract
  - arxiv
  - bibtex_show
  - html
  - pdf
  - selected
  - supp
  - blog
  - code
  - poster
  - slides
  - website
imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - .jpg
    - .jpeg
    - .png
    - .tiff
  output_formats:
    webp: '-quality 75%'
jekyll-diagrams: null
enable_google_analytics: true
enable_panelbear_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
academicons:
  version: 1.9.1
  integrity: sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg=
bootstrap:
  version: 4.6.2
  integrity:
    css: sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N
    js: sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct
fontawesome:
  version: 5.15.4
  integrity: sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=
jquery:
  version: 3.6.0
  integrity: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
mathjax:
  version: 3.2.0
masonry:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.20.0
  integrity:
    css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
    js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
popper:
  version: 2.11.2
  integrity: sha256-l/1pMF/+J4TThfgARS6KwWrk/egwuVvhRzfLAMQ6Ds4=
medium_zoom:
  version: 1.0.6
  integrity: sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM=
